import { Inter } from "next/font/google";
import "./globals.css";
import Menu, { LinkItem, MenuProps } from "../components/Menu"
import Header from "../components/Header"
import { ReactNode } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "crowemi",
  description: "Generated by create next app",
};

const menuItems: LinkItem[] = [
  { name: "home", route: "/" },
  { name: "about", route: "/about" },
  { name: "services", route: "/#services" }
]

interface Props {
  children?: ReactNode
}

export default function RootLayout({ children }: Props) {
  return (
    <html lang="en">
      <body>
        <Header />
        <Menu linkItems={menuItems} />
        {children}
      </body>
    </html>
  );
}
