import { Inter } from "next/font/google";
import "./globals.css";
import Menu from "./menu";
import Header from "./header"

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "crowemi",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
        {Header()}
        {Menu()}
        {children}
    </html>
  );
}
